### ISSUE TITLE
gh-pages project route not matching

### ISSUE THREAD

**Issue by JRJurman** [yoshuawuyts/sheet-router#76]
I'm building an app with choo, and my router looks like this:
```javascript
app.router([
  ['/', main],
]);
```
This works great when running locally or doing development, but when I push this to github pages, the project lives in a route off my github, `http://jrjurman.github.io/project-name/`, and I get an error that `project-name/` is not a matching route. 

I am able to use the default parameter to get a single route app working, but it doesn't solve the issue if there are multiple routes.

Is there a defined way to solve this?

**Comment by brechtpm** [comment]
Haven't been able to test it yet, but I think setting a baseUrl in your `index.html` should fix this:

    <head>
        <base href="http://jrjurman.github.io/project-name/">
        
    </head>

**Comment by JRJurman** [comment]
@brechtpm Just tried that, in the dev server it runs fine, but I still get the same error on gh-pages.

**Comment by yoshuawuyts** [comment]
This is similar in idea to
https://github.com/yoshuawuyts/sheet-router/issues/74. Your path is
technically not `/` but `/project-name`. Something you can do is run
through all routes recursively (before passing them to the .router()
method) and prefixing them with the base pathname you're mounting your
application on. It'd be cool if someone could write a package for that.
Hope this makes sense!

**Comment by brechtpm** [comment]
Apparently gh-pages doesn't support single-page apps out of the box. There are some [extensive hacks](http://spa-github-pages.rafrex.com/) out there to make it work though, so maybe you'd have some luck trying one of those.

**Comment by JRJurman** [comment]
@yoshuawuyts that makes sense...  I guess I could check what environment I'm building for, and prepend all the routes before sending it to sheet-router if I'm building for production. Currently, create-react-app looks for a `homepage` property in the package.json, which I now realize is probably how they solve this issue for their router. 

@brechtpm that's an awesome find... It might be a little overkill for some of the projects I'm working on :P
